server:
  port: 9527
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mdttest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.background.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug